# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dstl8 < Formula
  desc "CLI and TUI for the dstl8 observability platform"
  homepage "https://dstl8.ai"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/control-theory/dstl8/releases/download/v0.2.4/dstl8_0.2.4_darwin_amd64.tar.gz"
      sha256 "022e12644e32093fe46a3102a538dae3d21e1d792081b7070fd2cb5602f4fa94"

      define_method(:install) do
        bin.install "dstl8"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/control-theory/dstl8/releases/download/v0.2.4/dstl8_0.2.4_darwin_arm64.tar.gz"
      sha256 "d41cd456d34babb68b348035a5428b11ef5abfb7a2709ee707d149343da4becf"

      define_method(:install) do
        bin.install "dstl8"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/dstl8/releases/download/v0.2.4/dstl8_0.2.4_linux_amd64.tar.gz"
      sha256 "25639a44861b610689c1061f5cb73b92dc0cba37ca186abeeaf6eda8b9f72f8b"
      define_method(:install) do
        bin.install "dstl8"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/control-theory/dstl8/releases/download/v0.2.4/dstl8_0.2.4_linux_arm64.tar.gz"
      sha256 "63a8c18160952b3455ce4569a18d78dee7e40b923f8c109ef772095b7d16c323"
      define_method(:install) do
        bin.install "dstl8"
      end
    end
  end

  test do
    system bin/"dstl8", "version"
  end
end
